apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bot-deployment.yaml
  - bot-service.yaml
  - miniapp-deployment.yaml
  - miniapp-service.yaml
  - http-route.yaml

configMapGenerator:
  - name: yalom-bot-config
    envs:
      - config.env
