apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - telegram-admin-job.yaml

configMapGenerator:
  - name: yalom-bot-config
    literals:
      - YALOM_HTTP__HOST=0.0.0.0
      - YALOM_HTTP__PORT=3000
      - YALOM_TELEGRAM__WEBHOOK__URL=https://141.147.3.145/tg/webhook
      - RUST_LOG=warn,yalom_bot=info
