apiVersion: helm.cattle.io/v1
kind: HelmChart

metadata:
  name: external-secrets
  namespace: kube-system

spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 2.8.0

  targetNamespace: external-secrets
  createNamespace: true

  valuesContent: |-
    installCRDs: true
