apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: yalom-bot

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: oci-vault

  target:
    name: yalom-bot-secrets
    creationPolicy: Owner

  data:
    - secretKey: YALOM_TELEGRAM__TOKEN
      remoteRef:
        key: yalom-telegram-token

    - secretKey: YALOM_TELEGRAM__WEBHOOK__SECRET_TOKEN
      remoteRef:
        key: yalom-webhook-secret-token
