apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-store.yaml
  - external-secret.yaml

images:
  - name: ghcr.io/slava-nikulin/yalom-bot
    newTag: latest
