apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: oci-vault

spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.envjgeqnaagic.abtheljsrpzrev3ivbofsscn5raenq72qmartyd6dd4l2smodjybzx3ehdiq
      region: eu-frankfurt-1
      principalType: InstancePrincipal
